version: "3.9"

services:
  app:
    build: .
    container_name: todo-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - app/node_modules
  mongo:
    image: mongo:6
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
    mongo-data:
